- src/fosslight_scanner/fosslight_scanner.py
Print output file instead of path.
> Print output file instead of path

- requirements.txt
- src/fosslight_scanner/_get_input.py
- src/fosslight_scanner/common.py
- src/fosslight_scanner/fosslight_scanner.py
- Add the FOSSLight Reuse to run during analysis.
> Add a FOSSLight Reuse

- src/fosslight_scanner/fosslight_scanner.py
When calling FOSSLight Source Scanner, only ScanCode was used before, but modify it to analyze using all scanners.
> Change the options when analyzing the source

- README.md
- Update the README with additional Scanners.
- Add FOSSLight Reuse and FOSSLight Binary as Scanner.
- Add mode to the parameter.
> Update the README with additional Scanners

- src/fosslight_scanner/common.py
When analyzed as a link, Excel overwrites the output result to enter the OSS Name and Download location. At this time, when the column name you are looking for is not found, handle an exception so that a bug does not occur.
> Fix a bug where column names do not match when overwriting an excel

- src/fosslight_scanner/fosslight_scanner.py
If there is space in the link, fix the error that occurs during download.
- error message : `git clone - failed:malformed URL 'https://github.com/LGE-OSS/example '`
> Fix errors that occur when downloading link

- src/fosslight_scanner/fosslight_scanner.py
Fix the bug caused by not initializing the variable that outputs the default OSS Name.
> Fix errors when parsing with path

- .reuse/dep5
- requirements.txt
- setup.py
- src/fosslight_scanner/_help.py
- src/fosslight_scanner/_run_compare.py
- src/fosslight_scanner/cli.py
- src/fosslight_scanner/fosslight_scanner.py
- src/fosslight_scanner/resources/bom_compare.html
- tests/after.yaml
- tests/before.yaml
Add compare mode
- Compare two FOSSLight Report yaml
> Add compare mode

- src/fosslight_scanner/_run_compare.py
- src/fosslight_scanner/cli.py
- src/fosslight_scanner/fosslight_scanner.py
- tox.ini
Fix scanner support format and not to create csv.
- all, scanner mode support format : excel, yaml
> Fix scanner support format and not to create csv.

- README.md
- requirements.txt
- src/fosslight_scanner/_help.py
- src/fosslight_scanner/cli.py
- src/fosslight_scanner/fosslight_scanner.py
- Change FL Reuse to FL Prechecker
> Change FL Reuse to FL Prechecker

- src/fosslight_scanner/_run_compare.py
- src/fosslight_scanner/common.py
- src/fosslight_scanner/fosslight_scanner.py
Support yaml format of FOSSLight Report
> Support yaml format of FOSSLight Report

- .github/workflows/pull-request.yml
- README.md
- setup.py
Change the minimum required version of Python to 3.7.
Reason :
- From ScanCode v31.0.1, Python 3.7+ is required.
For this reason, the FOSSLight source scanner requires python 3.7.
> Change the required version of Python to 3.7

- src/fosslight_scanner/common.py
Fix a bug that incorrectly displays relative and absolute paths when outputting ScanCode json files.
> Fix absolute path related bugs

- requirements.txt
- src/fosslight_scanner/common.py
> Fix the fs output path

- src/fosslight_scanner/_help.py
- src/fosslight_scanner/fosslight_scanner.py
Multiple modes can be entered by separating them with ,.
ex. src,bin 
> Supports multiple input modes

- src/fosslight_scanner/_parse_setting.py
- src/fosslight_scanner/cli.py
- tests/setting.json
- tox.ini
Change the json key and value format.
> Change the json key and value format

- requirements.txt
- src/fosslight_scanner/fosslight_scanner.py
- Added the `simple_mode` parameter to include `FL source`, `dependency`, and `binary` in the FL Scanner output for a more comprehensive analysis.
- #102 
Before merging this PR, it is necessary to merge [this one](https://github.com/fosslight/fosslight_util/pull/173) first.
> Add simple_mode parameter to CoverItem constructor

- requirements.txt
- src/fosslight_scanner/_run_compare.py
- src/fosslight_scanner/common.py
- src/fosslight_scanner/fosslight_scanner.py
> Refactoring OSS item

- requirements.txt
- src/fosslight_scanner/fosslight_scanner.py
> Remove prechecker

- requirements.txt
- tests/requirements.txt
- tests/test__get_input.py
- tests/test__help.py
- tests/test__parse_setting.py
- tests/test__run_compare.py
- tests/test_cli.py
- tests/test_common.py
- tests/test_fosslight_scanner.py
- tox.ini
Change existing test to pytest
what I've done in this PR:
1. add tests/test__get_input.py
2. add tests/test__help.py
3. add tests/test__parse_setting.py
4. add tests/test__run_compare.py
5. add tests/test_cli.py
6. add tests/test_common.py
7. add tests/test_fosslight_scanner.py
8. change tox.ini
> Change the test code to use pytest

- requirements.txt
- src/fosslight_scanner/_help.py
- src/fosslight_scanner/_run_compare.py
- src/fosslight_scanner/cli.py
- src/fosslight_scanner/fosslight_scanner.py
- tests/test_cli.py
- tests/test_fosslight_scanner.py
> Support multi format and spdx

- src/fosslight_scanner/fosslight_scanner.py
- Print option name with error msg
> Print option name with error msg

- Dockerfile
Change base image to fix docker build error on macOS.
- Docker build error message : 
``` 
134.3 Collecting scancode-toolkit==32.2.* (from ***_source<3.0.0,>=2.1.4->***-scanner==2.1.1)
....
134.4   Downloading scancode_toolkit-32.2.0-cp38-none-any.whl.metadata (16 kB)
134.9 ERROR: No matching distribution found for extractcode-7z>=16.5.210525; extra == "full"
```
> Change base image to fix docker build error on macOS
