fosslight/fosslight_scanner

requirements.txt
Add the FOSSLight Util minimum version.
=> Add the FOSSLight Util minimum version

README.md, requirements.txt, src/fosslight_scanner/_help.py, src/fosslight_scanner/fosslight_scanner.py
- Change the output path of log, source.
- Delete raw data without the -r option.
- Change the FL Dependency main method to the latest version.
=> Change the output path of log, source

README.md, src/fosslight_scanner/_help.py, src/fosslight_scanner/fosslight_scanner.py
- Specify the output file name.
- Execute source and dependency analysis only when path is not null.
=> Specify the output file name

src/fosslight_scanner/_help.py, src/fosslight_scanner/fosslight_scanner.py
Add option (-t) for hiding the progress bar. 
=> Add option -t  for hiding the progress bar

requirements-dev.txt, requirements.txt, src/fosslight_scanner/_get_input.py, src/fosslight_scanner/_help.py, src/fosslight_scanner/fosslight_scanner.py, tox.ini
- Execute both FL Source and FL Dependency for the path with the -p option.
- Receive the path for FL Source and FL dependency only once in input mode.
=> Change the parameters related to the scanner path

src/fosslight_scanner/_help.py, src/fosslight_scanner/fosslight_scanner.py
Set the number of multi processes to analyze the source code with the -c option.
The default is set to maximum.
=> Add number of process to analyze as parameter

requirements.txt, src/fosslight_scanner/_get_input.py, src/fosslight_scanner/_help.py, src/fosslight_scanner/fosslight_scanner.py
- Add the FOSSLight Binary to run during analysis.
- Add the v option to print the version.
=> Add a FOSSLight Binary

setup.py, src/fosslight_scanner/_help.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py, tox.ini
Let the user choose which Scanner to analyze. 
|Mode|Description|
|------|---|
|  source        |   Run FOSSLight Source|
| dependency | Run FOSSLight Dependency|
|bin                | Run FOSSLight Binary|
|reuse           |  Run FOSSLight Reuse|
|all                |  Run all scanners (Default value)|
=> Support analysis mode

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
Move the txt file generated as a result of binary analysis to the output so that user can check it even when raw data is deleted.
=> Move the binary analysis result file to output

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
- Modify to print output file name
- Deal with format option error
=> Modify to print output file name

src/fosslight_scanner/_help.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/fosslight_scanner.py
Add an inputable value to mode.
- bin, binary : Run FOSSLight Binary
- src, source : Run FOSSLight Source
- dep, dependency : Run FOSSLight Dependency
- reuse : Run FOSSLight Reuse
- all : Run all the scanners.
=> Add an inputable value to mode

src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py
=> Apply f-string format

src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py, tox.ini
Extract the OSS name from the link.
- Github : https://github.com/{owner}/{repo} -> {owner}-{repo} 
- npm : www.npmjs.com/package/(package) -> npm:{package}
- npm : https://www.npmjs.com/package/@(group)/(package) ->  npm:@{group}/{package}
- pypi : https://pypi.org/project/(package) -> pypi:{package}
- Maven: https://mvnrepository.com/artifact/(group)/(artifact) -> {group}:{artifact}
- pub: https://pub.dev/packages/(package) -> pub:{package}
- Cocoapods: https://cocoapods.org/(package) -> cocoapods:{package}
=> Extract the OSS name from the link

src/fosslight_scanner/fosslight_scanner.py
Print download location when analyzing as link.
=> Print download location when analyzing as link

src/fosslight_scanner/fosslight_scanner.py
Run fosslight_source without installing it
=> Run fosslight_source without installing it

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
- Modify reuse input parameter
=> Modify reuse input parameter

src/fosslight_scanner/_help.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/fosslight_scanner.py
Replace 'y' option to 'p' option.
=> Replace 'y' option to 'p' option.

src/fosslight_scanner/_run_compare.py, src/fosslight_scanner/fosslight_scanner.py
=> Change the report file name

src/fosslight_scanner/fosslight_scanner.py
Fix the binary text copy issue
=> Fix the binary text copy issue

requirements-dev.txt, src/fosslight_scanner/_get_input.py, src/fosslight_scanner/fosslight_scanner.py
- Fix bug about dep. arg input when not dep. running
- Added importlib-metadata with specific version as a dependency for test on Python-3.7
=> Fix bug about dep. arg input when not dep. running

src/fosslight_scanner/_get_input.py, src/fosslight_scanner/fosslight_scanner.py
- Analyze current path if not input path
=> Analyze current path if not input path

src/fosslight_scanner/fosslight_scanner.py
Fix the output file msg if nothing scanned
=> Fix the output file msg if nothing scanned

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml
- Update version of package for actions
=> Update version of package for actions

.github/workflows/build-daily.yml
Add the cron job to check daily build
=> Add the cron job to check daily build

requirements.txt, src/fosslight_scanner/common.py
- Apply additional return val of 'parsing_yml'
=> Apply additional return val of 'parsing_yml'

src/fosslight_scanner/_help.py, src/fosslight_scanner/fosslight_scanner.py
Add the package name to result file and log
=> Add the package name to result file and log

.github/workflows/publish-release.yml
Update the git config for gh action
=> Update the git config for gh action

src/fosslight_scanner/_help.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py
Correct the source/bin scanner result
=> Correct the source/bin scanner result

requirements.txt, src/fosslight_scanner/_help.py, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py
Fix the correct mode bug for yaml format
=> Fix the correct mode bug for yaml format

src/fosslight_scanner/common.py
Modify exclude item not to compare for correct mode
=> Modify exclude item not to compare for correct mode

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
Fix the source analysis fail issue
=> Fix the source analysis fail issue

requirements.txt, src/fosslight_scanner/_help.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py
=> Generate ui mode result file

src/fosslight_scanner/fosslight_scanner.py
=> Fix the vulnerability

requirements.txt, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py
Include the parent directory for ScanCode format.
=> Include the parent directory for ScanCode

requirements.txt, src/fosslight_scanner/common.py
Print even files that were not detected for scancode json format.
=> Print even files that were not detected

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
- Change use of run_all_scanner to run_scanners to adopt change of FL Source
=> Fix importing from  fl source

.github/workflows/pull-request.yml
ref: #77
ref https://github.com/fosslight/fosslight/pull/969#issue-1868493271
When pr is opened fosslight scanner check commit message with own file.
Check commit message with common file in fosslight/.github
=> Fetch base-check-commit-message.yml from fosslight/.github

.github/workflows/build-daily.yml
Update supported python version
=> Update supported python version

src/fosslight_scanner/common.py
Support oss name with files.pythonhosted.org url
=> Support oss name with files.pythonhosted.org url

src/fosslight_scanner/common.py
Normalize pypi package name (PEP 0503)
=> Normalize pypi package name (PEP 0503)

requirements.txt, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py
Download the latest version of package url (pypi, npm, maven, pub)
=> Download the latest version of package url

src/fosslight_scanner/_help.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/fosslight_scanner.py
- Remove prechecker mode
- Remove FL Prechecker from all and default mode 
- Modify help msg
=> Remove FL Prechecker mode

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
Add detection summary message (cover sheet)
=> Add detection summary message (cover sheet)

requirements.txt, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py
- Add TLSH, SHA1 column for binary analysis
=> Add TLSH, SHA1 column for binary analysis

requirements.txt
- Modify FL Binary required ver. to 4.1.29
=> Modify FL Binary required ver. to 4.1.29

requirements.txt
- Update the requirements.txt
- fosslight_util >= 1.4.4
=> Update the requirements.txt

requirements.txt, src/fosslight_scanner/_get_input.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/fosslight_scanner.py, tox.ini
* Supports for scanning with two mode inputs
=> Supports for multiple modes

src/fosslight_scanner/common.py
=> Modify column name

src/fosslight_scanner/common.py
When merging src to bin, remove src info instead of excluding
=> When merging src to bin, remove src info instead of excluding

README.md, requirements.txt, src/fosslight_scanner/_help.py, src/fosslight_scanner/cli.py, src/fosslight_scanner/common.py, src/fosslight_scanner/fosslight_scanner.py, tox.ini
* Pass path to exclude arguments to each scanner
* Update help message and README
=> Supports for excluding paths from analysis

src/fosslight_scanner/fosslight_scanner.py
Allow more than two modes to be entered.
=> Allow more than two modes to be entered

README.md, src/fosslight_scanner/_help.py, src/fosslight_scanner/_parse_setting.py, src/fosslight_scanner/cli.py, tests/setting.json, tox.ini
* Add argument of applying setting from json file
* Upload setting.json for showing format and testing
* Leave comments for feature that excludes path
=> Supports for applying setting from json file

src/fosslight_scanner/fosslight_scanner.py
=> Remove to create bin.txt

src/fosslight_scanner/fosslight_scanner.py
=> Run with compressed file

src/fosslight_scanner/fosslight_scanner.py
Fix a bug related to path_to_exclude.
=> Fix a bug related to path_to_exclude

requirements.txt
Limit installation fosslight package
=> Limit installation fosslight package

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
Reverts fosslight/fosslight_scanner#119
=> Revert "Remove prechecker"

requirements.txt, src/fosslight_scanner/fosslight_scanner.py
=> Support cycloneDX format

src/fosslight_scanner/common.py
Fix json output error when not analyzing source.
=> Fix json output error when not analyzing source

.github/workflows/docker-build-push.yml
Update platform in docker build workflow.
=> Update platform in docker build workflow

src/fosslight_scanner/common.py
Fix ui mode error when analyzing only dependency
=> Fix ui mode error when analyzing only dependency

requirements.txt, src/fosslight_scanner/common.py
=> Add dep item in ui result

src/fosslight_scanner/common.py
=> Fix the correct bug

src/fosslight_scanner/fosslight_scanner.py
=> Fix the compare output bug
